runtime: go
api_version: go1

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: public/\1
  upload: public/(.*\.css)
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: public/\1
  upload: public/(.*\.js)
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: public/\1
  upload: public/(.*\.(bmp|gif|ico|jpeg|jpg|png))
- url: /(.*\.html)
  mime_type: text/html
  static_files: public/\1
  upload: public/(.*\.html)
- url: /(.+)/
  static_files: public/\1/index.html
  upload: public/(.+)/index.html
- url: /(.+)
  static_files: public/\1/index.html
  upload: public/(.+)/index.html
- url: /
  static_files: public/index.html
  upload: /
- url: /.*
  script: _go_app

skip_files: |
  ^(.*/)?(
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (\..*)|
  (manage\.py)|
  (README\.md)|
  (LICENSE)|
  (archetypes\/.*)|
  (content\/.*)|
  (data\/.*)|
  (layouts\/.*)|
  (static\/.*)|
  (themes\/.*)|
  (\.git\/.*)|
  (\.gitignore)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (config\.yaml)|
  )$